[benchmark]
dataSize=1 #填数字 单位KB 例如1 表示单条数据的总大小为1kb  # This indicates the total size of a single data record is 1024 kilobytes.
dbs=[]  #要压测的数据列表  例 ["mysql","dm","kingbase","shentong","mongodb"] # A list of data sources for load testing, e.g.: ["mysql","dm","kingbase","shentong","mongodb"]"
executeSize=500000   #执行总请求数的大小  Total size of executed requests
threads=300  # Concurrency Threads Count
[mysql]
name="k8syanshi"
password="kI8U1OfYmKlh63VP"
ip ="192.168.210.156"
port="11306"

[dameng]
name="SYSDBA"
password="SYSDBA001"
ip ="192.168.85.23"
port="25236"

[kingBase]
name=""
password=""
ip =""
port=""
instance=""

[shenTong]
name=""
password=""
ip =""
port=""
instance=""

[mongodb]
name="" # 可选
password="" #可选
ip =""
port=""