dataSize: 1 #填数字 单位KB 例如1 表示单条数据的总大小为1kb
dbs: mysql,kingbase # 要压测的数据列表 逗号分割 例 mysql,dm,kingbase,shentong
executeSize : 10000

mysql:
   name:
   password:
   ip :
   port:
dameng:
   name:
   password:
   ip :
   port:
kingBase:
   name:
   password:
   ip :
   port:
   instance :
shenTong:
   name:
   password:
   ip :
   port:
   instance :